version: '3.10'
services:
  backend:
    build:
      context: .
    container_name: chatform
    ports:
      - "8000:8000"
      - "12345:12345"  
    env_file:
      - .env
    depends_on:
      - postgres-db
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    networks:
      - dockernet

  postgres-db:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dockernet

volumes:
  postgres-data:

networks:
  dockernet:
    external: true
    driver: bridge