# Generated by Django 5.0.1 on 2024-01-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_rename_sender_backmessage_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontmessage',
            old_name='sender',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='username',
        ),
    ]
