# Generated by Django 5.0.1 on 2024-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_room_remove_message_receiver_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomBack',
        ),
        migrations.AlterModelOptions(
            name='roomback',
            options={'verbose_name': 'Комната Backend', 'verbose_name_plural': 'Комната Backend'},
        ),
    ]
