# Generated by Django 5.0.1 on 2024-01-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_rename_roomback_rooms_backmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
