# Generated by Django 5.0.1 on 2024-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_rooms_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
