# Generated by Django 5.0.1 on 2024-01-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_backmessage_options_frontmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
