# Generated by Django 5.0.1 on 2024-01-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='frontmessage',
            name='room',
        ),
    ]
