# Generated by Django 5.0.1 on 2024-01-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_remove_backmessage_room_remove_frontmessage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backmessage',
            old_name='sender',
            new_name='username',
        ),
    ]
